apiVersion: v1
kind: Pod
metadata:
  name: secret-test
  namespace: dev
spec:
  containers:
  - image: ubunutu
    name: secret-test
    env:
      - name: NAME
        value: "nginx"
      - name: DEBUG
        value: "FALSE"
    resources:
      requests:
        cpu: "125m"
        memory: "64Mi"
  serviceAccountName: default