apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: ClusterIP
  externalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/name: nginx
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 80 #http-web-svc