apiVersion: v1
kind: ConfigMap
metadata:
 name: simple-cm
 namespace: pistis-tech-hub
data:
  PORT: "80"
  DEBUG:  "FALSE"

---

apiVersion: v1
kind: Secret
metadata:
  name: db-creds
  namespace: pistis-tech-hub
data:
  password: cGFzc3dvZGhoZGhzODg4JiYm
  username: cGlzdGlz
type: Opaque