apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-daemonset
  namespace: default
spec:
  selector:
    matchLabels:
      name: fluentd-daemonset
  template:
    metadata:
      labels:
        name: fluentd-daemonset
    spec:
      containers:
        - name: fluentd-daemonset
          image: quay.io/fluentd_elasticsearch/fluentd:latest