apiVersion: v1
kind: Pod
metadata:
  name: secret-test
  namespace: pistis-tech-hub
spec:
  containers:
  - image: nginx:latest
    name: secret-test
    env:
      - name: NAME
        value: "nginx"
      - name: DEBUG
        value: "FALSE"
    resources:
      requests:
        cpu: "125m"
        memory: "64Mi"
  serviceAccountName: default